FROM python:3.12-slim

ENV PYTHONUNBUFFERED True

# set the working directory
WORKDIR /usr/src/app

# install dependencies
COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

# Set PYTHONPATH to include the src directory
ENV PYTHONPATH=/usr/src/app/src

# copy src code
COPY ./src ./src

EXPOSE 4000

# start the server
CMD ["sh", "-c", "uvicorn src.main_chatwoot:app --host 0.0.0.0 --port 4000 --proxy-headers"]